paths:
  base_dir: "data/processed"
  # Se for rodar os topicos e lftk de dfs diferentes descomente essas linhas e mude no codigo
  #topics_file: "ads_with_lftk.parquet"
  #lftk_file: "ads_with_lftk.parquet"
  file: "ideology_with_lftk.parquet"
  output_ranking: "data/processed/ranking_gini_ideo_pt.csv"
  output_top10: "data/processed/ranking_gini_ideo_top10_pt.csv"

gini:
  n_thresholds: 50
  top_n: 10
  lang: 'pt'
  corr_threshold: 0.7

columns:
  text: "text_clean"
  target: "ideologia"
  primary_key: "ad_id"
  num_topics: 
   - "direita"
   - "centro-direita"
   - "centro-esquerda"
   - "esquerda"
  lftk_columns:
  - t_word
  - t_stopword
  - t_punct
  - t_syll
  - t_syll2
  - t_syll3
  - t_uword
  - t_sent
  - t_char
  - a_word_ps
  - a_char_ps
  - a_char_pw
  - a_syll_ps
  - a_syll_pw
  - a_stopword_ps
  - a_stopword_pw
  - t_kup
  - t_bry
  - t_subtlex_us_zipf
  - a_kup_pw
  - a_bry_pw
  - a_kup_ps
  - a_bry_ps
  - a_subtlex_us_zipf_pw
  - a_subtlex_us_zipf_ps
  - t_n_ent
  - t_n_ent_person
  - t_n_ent_norp
  - t_n_ent_fac
  - t_n_ent_org
  - t_n_ent_gpe
  - t_n_ent_loc
  - t_n_ent_product
  - t_n_ent_event
  - t_n_ent_art
  - t_n_ent_law
  - t_n_ent_language
  - t_n_ent_date
  - t_n_ent_time
  - t_n_ent_percent
  - t_n_ent_money
  - t_n_ent_quantity
  - t_n_ent_ordinal
  - t_n_ent_cardinal
  - a_n_ent_pw
  - a_n_ent_person_pw
  - a_n_ent_norp_pw
  - a_n_ent_fac_pw
  - a_n_ent_org_pw
  - a_n_ent_gpe_pw
  - a_n_ent_loc_pw
  - a_n_ent_product_pw
  - a_n_ent_event_pw
  - a_n_ent_art_pw
  - a_n_ent_law_pw
  - a_n_ent_language_pw
  - a_n_ent_date_pw
  - a_n_ent_time_pw
  - a_n_ent_percent_pw
  - a_n_ent_money_pw
  - a_n_ent_quantity_pw
  - a_n_ent_ordinal_pw
  - a_n_ent_cardinal_pw
  - a_n_ent_ps
  - a_n_ent_person_ps
  - a_n_ent_norp_ps
  - a_n_ent_fac_ps
  - a_n_ent_org_ps
  - a_n_ent_gpe_ps
  - a_n_ent_loc_ps
  - a_n_ent_product_ps
  - a_n_ent_event_ps
  - a_n_ent_art_ps
  - a_n_ent_law_ps
  - a_n_ent_language_ps
  - a_n_ent_date_ps
  - a_n_ent_time_ps
  - a_n_ent_percent_ps
  - a_n_ent_money_ps
  - a_n_ent_quantity_ps
  - a_n_ent_ordinal_ps
  - a_n_ent_cardinal_ps
  - simp_adj_var
  - simp_adp_var
  - simp_adv_var
  - simp_aux_var
  - simp_cconj_var
  - simp_det_var
  - simp_intj_var
  - simp_noun_var
  - simp_num_var
  - simp_part_var
  - simp_pron_var
  - simp_propn_var
  - simp_punct_var
  - simp_sconj_var
  - simp_sym_var
  - simp_verb_var
  - simp_space_var
  - root_adj_var
  - root_adp_var
  - root_adv_var
  - root_aux_var
  - root_cconj_var
  - root_det_var
  - root_intj_var
  - root_noun_var
  - root_num_var
  - root_part_var
  - root_pron_var
  - root_propn_var
  - root_punct_var
  - root_sconj_var
  - root_sym_var
  - root_verb_var
  - root_space_var
  - corr_adj_var
  - corr_adp_var
  - corr_adv_var
  - corr_aux_var
  - corr_cconj_var
  - corr_det_var
  - corr_intj_var
  - corr_noun_var
  - corr_num_var
  - corr_part_var
  - corr_pron_var
  - corr_propn_var
  - corr_punct_var
  - corr_sconj_var
  - corr_sym_var
  - corr_verb_var
  - corr_space_var
  - simp_ttr
  - root_ttr
  - corr_ttr
  - bilog_ttr
  - uber_ttr
  - simp_ttr_no_lem
  - root_ttr_no_lem
  - corr_ttr_no_lem
  - bilog_ttr_no_lem
  - uber_ttr_no_lem
  - n_adj
  - n_adp
  - n_adv
  - n_aux
  - n_cconj
  - n_det
  - n_intj
  - n_noun
  - n_num
  - n_part
  - n_pron
  - n_propn
  - n_punct
  - n_sconj
  - n_sym
  - n_verb
  - n_space
  - n_uadj
  - n_uadp
  - n_uadv
  - n_uaux
  - n_ucconj
  - n_udet
  - n_uintj
  - n_unoun
  - n_unum
  - n_upart
  - n_upron
  - n_upropn
  - n_upunct
  - n_usconj
  - n_usym
  - n_uverb
  - n_uspace
  - a_adj_pw
  - a_adp_pw
  - a_adv_pw
  - a_aux_pw
  - a_cconj_pw
  - a_det_pw
  - a_intj_pw
  - a_noun_pw
  - a_num_pw
  - a_part_pw
  - a_pron_pw
  - a_propn_pw
  - a_punct_pw
  - a_sconj_pw
  - a_sym_pw
  - a_verb_pw
  - a_space_pw
  - a_adj_ps
  - a_adp_ps
  - a_adv_ps
  - a_aux_ps
  - a_cconj_ps
  - a_det_ps
  - a_intj_ps
  - a_noun_ps
  - a_num_ps
  - a_part_ps
  - a_pron_ps
  - a_propn_ps
  - a_punct_ps
  - a_sconj_ps
  - a_sym_ps
  - a_verb_ps
  - a_space_ps
  - fkre
  - fkgl
  - fogi
  - smog
  - cole
  - auto
  - rt_fast
  - rt_average
  - rt_slow